name: Relay checks status
on:
  check_suite:
    types: [completed]
  pull_request:
    types: [opened, synchronize]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success' }}
        with:
          labels: checks:green
      # Optional: you could post a short comment here for human visibility
